Fix Micro build errors
With standard variant multiple errors e.g.
error: ‘RXLED1’ was not declared in this scope

Switching to micro results in
cores/arduino/PluggableUSB.cpp:102:(.text+0x53c): undefined reference to
`__cxa_guard_acquire'
cores/arduino/PluggableUSB.cpp:102:(.text+0x55c): undefined reference to
`__cxa_guard_release'